version: 2.1

jobs:
  # Job pour la construction et les tests de l'application Node.js
  build:
    docker:
      - image: circleci/node:16  # Utilisation d'une image Docker officielle Node.js
    steps:
      - checkout  # Récupère le code du dépôt
      - setup_remote_docker:  # Permet l'exécution de Docker sur la machine virtuelle CircleCI
          version: 20.10.7  # Version de Docker à utiliser
          docker_layer_caching: true  # Active le caching pour accélérer les builds
      - run:
          name: Build Docker Image
          command: |
            docker build -t mon-app-node .  # Crée l'image Docker à partir de votre Dockerfile
      - run:
          name: Run Tests
          command: |
            docker run mon-app-node npm test  # Exécute les tests dans l'image Docker créée

  # Job pour construire et pousser l'image Docker sur Docker Hub
  dockerize_and_push:
    docker:
      - image: docker:19.03.12  # Utilisation de l'image Docker officielle pour la gestion des images
    steps:
      - checkout  # Récupère le code du dépôt
      - setup_remote_docker:
          version: 27.4.0  # Version de Docker à utiliser
          docker_layer_caching: true  # Active le caching pour accélérer les builds
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/$DOCKER_REPO:$CIRCLE_SHA1 .  # Crée l'image Docker avec un tag unique basé sur le commit
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin  # Authentifie Docker Hub
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/$DOCKER_REPO:$CIRCLE_SHA1  # Pousse l'image Docker sur Docker Hub

workflows:
  version: 2
  build-and-test:
    jobs:
      - build  # Le job pour la construction et les tests
      - dockerize_and_push:  # Le job pour pousser l'image Docker sur Docker Hub
          requires:
            - build  # Le job de poussée sera exécuté après le succès du job de construction et tests

