version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t mon-app-node .
      - run:
          name: Run Tests
          command: |
            docker run mon-app-node npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
